spring.application.name=ordershopx-backend


# CONEXIÓN A BASE DE DATOS RENDER
spring.datasource.url=jdbc:postgresql://dpg-d9crkiihil2s73ao55ig-a.ohio-postgres.render.com:5432/ordershopx?sslmode=require
spring.datasource.username=admin_osx
spring.datasource.password=ZNCUCEXMjOZTzCpBmlspSKKVhLwW3WqQ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE (En 'none' para proteger la BD que creamos con SQL)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SECURITY
spring.security.user.name=admin
spring.security.user.password=1234

# JWT
jwt.secret=mi_clave_super_segura_que_no_debe_subirse_a_git_y_tiene_mas_de_64_caracteres_123456789

# SERVER
server.address=0.0.0.0
server.port=${PORT:8080}

# CONFIGURACION DE CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ordershopx2026@gmail.com
spring.mail.password=lnadngcmfaeoduwf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# CONFIGURACION DE ENLACES
app.mobile.deeplink=https://spicy-showers-cry.loca.lt/activar 

# IA GEMINI
gemini.api.key=AQ.Ab8RN6KMfOzdiLSAfu4JZ3QrI0X4fNpn4FJ1htq-0jKD42OZAQ