spring.application.name=ordershopx-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/OrderShopX
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SECURITY
spring.security.user.name=admin
spring.security.user.password=1234

#JWT
jwt.secret=mi_clave_super_segura_que_no_debe_subirse_a_git_y_tiene_mas_de_64_caracteres_123456789

# SERVER
server.address=0.0.0.0
